---

- name: Setting up Nagios Repo for Softlayer
  hosts: "dev-chad"
  remote_user: "Chad.Perry1"
  become: true
  become_user: root
  gather_facts: true
  vars:
    VAR_FILE: nagios-proxy.yml

  vars_files:
    - vars/{{ VAR_FILE }}

  tasks:
    - name: Block text added
      blockinfile:
        path: /etc/yum.conf
        insertafter: '^distroverpkg=centos-release'
        block: |
          ip_resolve=4
          proxy_username=
          proxy_password=
          proxy=
      tags: softlayerProxy

    - name: Adding proxy_username to /etc/yum.conf
      lineinfile:
        path: /etc/yum.conf
        regexp: '^proxy_username='
        line: "proxy_username={{ PROXY_USERNAME }}"
      tags: softlayerProxy

    - name: Adding proxy_password to /etc/yum.conf
      lineinfile:
        path: /etc/yum.conf
        regexp: '^proxy_password='
        line: "proxy_password={{ PROXY_PASSWORD }}"
      tags: softlayerProxy

    - name: Adding proxy server url
      lineinfile:
        path: /etc/yum.conf
        regexp: '^proxy='
        line: "proxy={{ PROXY_SERVER }}"
        owner: root
        group: root
        mode: 0644
      tags: softlayerProxy