---
- name: Setting root password
  hosts: dev-chad
  remote_user: '{{ USER }}'
  gather_facts: true
  
  tasks:  
    - name: Add labeled user
      user:
        name: "root"
#       uid: "{{ item.1.validation.employee_serial[2:6] }}"
     ## upassword is passed as argument to playbook: '-e "upassword=<yourpass>"'
        password: "{{ upassword | password_hash('sha512') }}"
        home: /home/{{ item.1.account }}
        comment: "{{ item.1.gecoslabel }}"
        state: present
        append: yes
        groups: "{{ item.1.account }}, {{ DOCKER_GROUP }}"
      with_subelements:
        - '{{ identity_details.results }}'
